### ISSUE TITLE
Translations are required, although the required option is not set

### ISSUE THREAD

**Issue by OliverTe** [mvenghaus/filament-plugin-translatable-inline#2]
Using the following code to show an input field. Note, there is **no** required option attached to the TextInput.

TranslatableContainer::make(
     Forms\Components\TextInput::make('description_short')
)

Expectation: neither the value for the main locale nor the other locales are necessary to enter, as ->required() is not given for the TextInput component.

Issue: I cannot save the form, as the form expects the value for the main locale to be entered. I have to add ->onlyMainLocaleRequired() to the TranslatableContainer to be able to save the form when all values for this input are empty.

Expectation: when there is no ->required() option set for the input component, it shall not be necessary to add ->onlyMainLocaleRequired() option to the container to successfully pass validation.

**Comment by mvenghaus** [comment]
Hey @OliverTe ,

thx for reporting! I released a new version where this is fixed.

Regards
Marcus
