### ISSUE TITLE
Bug : Column not found: 1054 Unknown column 'en' in 'where clause' 

### ISSUE THREAD

**Issue by aeq-dev** [mvenghaus/filament-plugin-translatable-inline#4]
After upgrading to latest version : 
![Screenshot from 2024-02-05 10-18-15](https://github.com/mvenghaus/filament-plugin-translatable-inline/assets/81385994/33371f53-559a-4c52-b3b5-f8378146da36)

**Comment by mvenghaus** [comment]
can you give a little more context please .. and you you have

use Translatable;

from spatie in your resource?

**Comment by aeq-dev** [comment]
It works fine in v3.0.3 
I've just downgraded it.

**Comment by mvenghaus** [comment]
can your share the part of your code?

**Comment by aeq-dev** [comment]
Let's discuss on discord plugin channel

**Comment by aeq-dev** [comment]
Hello, any update here ? thanks :)

**Comment by mvenghaus** [comment]
hey @aeq-dev .. sorry daily work .. just write me in discord "mvenghaus_12471"
