### ISSUE TITLE
getTranslatableLocales is ignored

### ISSUE THREAD

**Issue by bamod33** [mvenghaus/filament-plugin-translatable-inline#5]
Hi, thanks for the plugin.

But in the resource, if you add: 

```
    public static function getTranslatableLocales(): array
    {
        return ['en', 'es_CO', 'es'];
    }
```
The plugin ignores that, however using the "regular" Spatie Translatable plugin works. Could you check it please? Thanks

**Comment by mvenghaus** [comment]
Hey @bamod33,

thx for reporting!

I've released a new version .. please check if everything is working now.

**Comment by bamod33** [comment]
Yep @mvenghaus 

Great update, now it works like a charm :)

Well done, thanks so much
